drop table users;
drop table wallet;
drop table wallet_history;
drop table product;
drop table inventory;
drop table cart_item;
drop table orders;
drop table order_item;

create table users
(
    seq_id   bigint generated by default as identity,
    user_key uuid,
    name     varchar(100),
    address  varchar(255),
    primary key (seq_id)
);
create table wallet
(
    id          bigint generated by default as identity,
    balance     bigint,
    created_at  timestamp(6),
    modified_at timestamp(6),
    user_id     bigint,
    primary key (id)
);
create table wallet_history
(
    id         uuid not null,
    amount     bigint,
    created_at timestamp(6),
    user_id    bigint,
    type       varchar(255) check (type in ('CHARGE', 'USE')),
    primary key (id)
);
create table product
(
    created_at  timestamp(6),
    modified_at timestamp(6),
    price       bigint       not null,
    product_id  bigint generated by default as identity,
    name        varchar(100) not null,
    primary key (product_id)
);
create table inventory
(
    product_id    bigint not null,
    current_stock integer,
--     version       bigint,
    created_at    timestamp(6),
    modified_at   timestamp(6),
    primary key (product_id)
);
create table cart_item
(
    quantity    integer,
    created_at  timestamp(6),
    modified_at timestamp(6),
    product_id  bigint not null,
    seq_id      bigint generated by default as identity,
    user_id     bigint,
    primary key (seq_id)
);
create table orders
(
    product_quantity integer,
    order_at         timestamp(6),
    seq_id           bigint generated by default as identity,
    total_price      bigint,
    order_id         uuid,
    user_id          uuid,
    payment_type     varchar(20) check (payment_type in ('WALLET')),
    address          varchar(255),
    transaction_id   varchar(255),
    primary key (seq_id)
);
create table order_item
(
    quantity     integer,
    order_at     timestamp(6),
    order_id     bigint not null,
    price        bigint,
    product_id   bigint not null,
    order_status varchar(255) check (order_status in
                                     ('PAID', 'ORDER_CONFIRM', 'DELIVERY_WAIT', 'DELIVERY',
                                      'DELIVERY_COMPLETED', 'ORDER_COMPLETED')),
    primary key (order_id, product_id)
);

create index idx_status_order_at on order_item (order_status, order_at);

insert into users(user_key, name, address) values('54211913-3695-4c19-85fb-28fe844d32c7', 'kim','강남');